#!/usr/bin/env perl
use 5.14.0;
use warnings;
eval 'exec /usr/local/bin/perl  -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
our $VERSION = 0.01;
use Perl5::Dist::Backcompat;
use Getopt::Long qw( GetOptions );
use File::Temp qw( tempdir );
#use Data::Dump qw( dd pp );

##### CHECK ENVIRONMENT #####

my ($perl_workdir, $path_to_perls, $tarball_dir, $host,
    $verbose, $cat_summaries) = ('') x 6;
my @distros_requested = ();
GetOptions(
    "perl_workdir=s"    => \$perl_workdir,
    "path_to_perls=s"   => \$path_to_perls,
    "tarball_dir=s"     => \$tarball_dir,
    "verbose"           => \$verbose,
    "distro=s"          => \@distros_requested,
    "host=s"            => \$host,
    "cat_summaries"     => \$cat_summaries,
) or die "Unable to get command-line options: $!";

my @wanthyphens = ();
for my $d (@distros_requested) {
    if ($d =~ m/::/) {
        push @wanthyphens, $d;
    }
}
if (@wanthyphens) {
    warn "$_: supply distribution name in 'Some-Distro' format, not 'Some::Distro'"
        for @wanthyphens;
    die "'distro' switch in incorrect format: $!";
}

my $self = Perl5::Dist::Backcompat->new( {
    perl_workdir    => $perl_workdir,
    path_to_perls   => $path_to_perls,
    tarball_dir     => $tarball_dir,
    verbose => 1,
} );

$self->init();

$self->categorize_distros();

$self->show_makefile_pl_status();

my @distros_for_testing = $self->get_distros_for_testing(\@distros_requested);

my @perls = $self->validate_older_perls();

say "Beginning processing of requested distros;\n  this will take some time ...";

my $debugdir = tempdir();
$self->test_distros_against_older_perls($debugdir);

$self->print_distro_summaries({ cat_summaries => $cat_summaries });

say "\nFinished!" if $verbose;

=head1 NAME

p5-dist-backcompat - Will changes to F<dist/> build on older C<perl>s?

=head1 SYNOPSIS

TK

=head1 PREREQUISITES

F<perl> 5.14.0 or newer, with the following modules installed from CPAN:

=over 4

=item * F<Data::Dump>

=item * F<File::Copy::Recursive::Reduced>

=back

=head1 COMMAND-LINE SWITCHES

=over 4

=item * C<--verbose>

Flag.  Extra helpful output on F<STDOUT>.

=item * C<--distro>

Switch-parameter pair.  Parameter should be hyphen-separated name of directory
under F</dist>, I<e.g.>, C<ExtUtils-ParseXS>, not C<ExtUtils::ParseXS>.  May
be called more than once, I<e.g.>:

    --distro Search-Dict --distro Safe --distro=Data-Dumper

=item * C<--host>

Switch-parameter pair.  Parameter should be the string returned by the system
F<hostname> call.  Defaults to C<dromedary.p5h.org>.

=item * C<--path_to_perls>

Switch-parameter pair.  Parameter should be an absolute path to the directory
holding binary executables of older F<perl>s.  Defaults to
F</media/Tux/perls-t/bin>.

=item * C<--perl_workdir>

Switch-parameter pair.  Parameter should be an absolute path to the directory
holding a F<git> checkout of the Perl 5 core distribution; user must checkout
branch, tag or commit in that directory as needed.

=item * C<--cat_summaries>

Flag.  When set to true, will direct method C<print_distro_summaries()> to
concatenate all summaries on STDOUT.

=back

=cut

__END__

